apiVersion: v1
kind: Service
metadata:
  name: express-api-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: express-api
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
