apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 80 #specifies the port that the container is listening on. This port is only accessible within the pod, and it is not exposed to the cluster or the outside world.
